language: minimal
dist: xenial

env:
  - FINANCEAGER_BACKEND=master FINANCEAGER_FRONTEND=master

addons:
  apt:
    packages:
    - python3-venv

before_script:
  - echo backend frontend > result.txt
  - ./prepare.sh

script:
  - echo $FINANCEAGER_BACKEND $FINANCEAGER_FRONTEND >> result.txt
  - ./run.sh
  - echo compatible >> result.txt

after_script:
  - cat result.txt

notifications:
    email:
        on_success: never
