language: minimal
dist: xenial

env:
  - FINANCEAGER_BACKEND=master FINANCEAGER_FRONTEND=master

addons:
  apt:
    packages:
    - python3-venv

before_script: ./prepare.sh

script: ./run.sh

after_success:
  - echo -e "Compatible: Backend $FINANCEAGER_BACKEND with $FINANCEAGER_FRONTEND"

after_failure:
  - echo -e "Incompatible: Backend $FINANCEAGER_BACKEND with $FINANCEAGER_FRONTEND"

notifications:
    email:
        on_success: never
