language: minimal
dist: xenial

cache:
  directories:
  - $HOME/.cache/pip

addons:
  apt:
    packages:
    - python3-venv

before_script:
  - echo backend frontend status > result.txt
  - ./prepare.sh

script:
  - ./run.sh

after_script:
  - cat result.txt

notifications:
    email:
        on_success: never
