#!/usr/bin/env python

import unittest
import sys
import os

# Make test modules of relevant repo available
sys.path.insert(0, os.path.expanduser('~/frontend/test'))
from test_cli import CliFlaskTestCase, suite

# Patch function because webservice is separately launched
CliFlaskTestCase.launch_server = lambda: 0

test_runner = unittest.TextTestRunner(verbosity=2)
result = test_runner.run(suite())
sys.exit(0 if result.wasSuccessful() else 1)
