#!/usr/bin/env python

import unittest
import sys
import os

from test_cli import CliFlaskTestCase, suite

# Patch function because webservice is separately launched
CliFlaskTestCase.launch_server = lambda: 0

test_runner = unittest.TextTestRunner(verbosity=2)
result = test_runner.run(suite())
sys.exit(0 if result.wasSuccessful() else 1)
