#!/usr/bin/env python

import unittest

import test_cli

# Patch function because webservice is separately launched
test_cli.CliFlaskTestCase.launch_server = lambda: 0

unittest.main(test_cli, verbosity=2)
